package by.training.controller.command;

public enum CommandName {
    SORT_PARAGRAPH_BY_COUNT_OF_SENTENCE,
    SORT_WORD_IN_SENTENCE_BY_LENGTH,
    SORT_SENTENCE_BY_COUNT_OF_LEXEME,
    SORT_LEXEME_IN_SENTENCE_BY_CHAR,
    ORIGINAL_TEXT,
    WRONG_REQUEST
}
