package by.training.controller.command;

/**
 * Enum command which the application supports.
 */
public enum CommandName {
    INDEX,
    SHOW,
    REGISTRATION,
    LOGIN,
    SEARCH,
    LOGOUT,
    MY_SERIAL,
    LIKED,
    RATING,
    PROFILE,
    LANGUAGE,
    WRONG_REQUEST,
    ADMIN_SERIAL,
    ADMIN_GENRE,
    ADMIN_COUNTRY,
    ADMIN_STUDIO,
    ADMIN_USER,
    SAVE_SERIAL,
    ADD_USER,
    SAVE_GENRE,
    SAVE_STUDIO,
    CHANGE_PASSWORD,
    CHANGE_ROLE,
    SAVE_COMMENT,
    DELETE_GENRE,
    DELETE_SERIAL,
    SAVE_COUNTRY,
    DELETE_COUNTRY,
    DELETE_STUDIO,
    DELETE_COMMENT,
    CHANGE_AVATAR,
    WATCH_SERIAL,
    STOP_WATCH_SERIAL,
    LIKE,
    DISLIKE,
    ERROR,
}
